---
- name: Install and start httpd
  hosts: production
  become: root
  
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present
      
  - name: Start httpd
    service:
      name: httpd
      state: started